spring.application.name=UberBackendAuth

server.port=7070

spring.datasource.url=jdbc:mysql://localhost:3306/uber_db_local

spring.datasource.username=root

spring.datasource.password=12345678

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

logging.level.org.springframework.data=DEBUG

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

spring.security.user.name=user
spring.security.user.password=12345678

cookie.expiry=36000
jwt.expiry=36000
jwt.secret=12342353262335241341342978y1234874t1237841237894tr123784gr13789gh123978cg872fg8yfgb8qyfggb82gcdb12b8789281379bdn28139